version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/HAPOOM-BE
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      runas: ubuntu
